### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by sakalu** [dstl/Stone-Soup-Notebooks#5]
Hi,
I got the following error when I executed the *.ipynb on Notebooks.
Appreciate if can advise. Thanks!

==============================================
from stonesoup.reader.generic import CSVDetectionReader
  File "stonesoup\base.py", line 108
    def __init__(self, cls, *, default=inspect.Parameter.empty, doc=None,
                             ^
SyntaxError: invalid syntax

**Comment by sdhiscocks** [comment]
@sakalu What version of Python are you using? I think this error would come up with Python 2.7. Stone Soup only supports Python 3.5+.

There is a [Stone Soup room on Gitter](https://gitter.im/dstl/Stone-Soup) where you can ask for help as well.

**Comment by sakalu** [comment]
@sdhiscocks 
Hi Steven,

Thank you for your reply. Yes, this error came up with the version of Python 2.7
This issue has been solved in Python 3.  Thanks for your help.

Regards,
Saka
