### ISSUE TITLE
JPDA Notebook, possible issue, incomplete plot

### ISSUE THREAD

**Issue by apiszcz** [dstl/Stone-Soup-Notebooks#7]
Started to work through the notebook at https://stonesoup.readthedocs.io/en/latest/auto_tutorials/08_JPDATutorial.html
The first cell is producing an partial plot of the ground truth.
The upper left corner appears and the remaining plot area is blank. I tried a refresh with the Home button.
It is possible my version or environment is the issue. However all prior notebooks plot correctly.

![2020-07-19T061758_575_1152](https://user-images.githubusercontent.com/1430861/87872568-ba349e80-c987-11ea-8e0a-e9b065d9b59a.png)

![2020-07-19T061918_929_1072](https://user-images.githubusercontent.com/1430861/87872593-e3552f00-c987-11ea-8add-a474d1fa0e55.png)

**Comment by sdhiscocks** [comment]
Please see up to date notebooks on [Stone Soup documentation](https://stonesoup.rtfd.io/)
